### ISSUE TITLE
Missing classes errors with R8 full mode using Tink in Android

### ISSUE THREAD

**Issue by tonidero** [tink-crypto/tink-java#7]
**Help us help you**

We'd like to know more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Describe the bug:**

After updating our Android SDK to R8 full mode (as part of the Android Gradle Plugin 8.0 upgrade), we started seeing some missing classes errors:
```
Missing class com.google.errorprone.annotations.CanIgnoreReturnValue (referenced from: com.google.crypto.tink.subtle.Ed25519$XYZ com.google.crypto.tink.subtle.Ed25519$XYZ.fromPartialXYZT(com.google.crypto.tink.subtle.Ed25519$XYZ, com.google.crypto.tink.subtle.Ed25519$PartialXYZT) and 1 other context)
Missing class com.google.errorprone.annotations.Immutable (referenced from: com.google.crypto.tink.util.Bytes)
```

Adding the following to our proguard rules works around the issue:
```
-dontwarn com.google.errorprone.annotations.CanIgnoreReturnValue
-dontwarn com.google.errorprone.annotations.Immutable
```
But these proguard rules should be part of the Tink library.

**What was the expected behavior?**

Minified builds in Android would continue working without build issues after upgrading to AGP 8.0

**How can we reproduce the bug?**

We currently only use the `Ed25519Verify` class from Tink in our project like this:

```
class SignatureVerifier(publicKey: ByteArray) {

    private val verifier = Ed25519Verify(publicKey)

    fun verify(signatureToVerify: ByteArray, messageToVerify: ByteArray): Boolean {
        return try {
            verifier.verify(signatureToVerify, messageToVerify)
            true
        } catch (_: GeneralSecurityException) {
            false
        }
    }
}
```

**Do you have any debugging information?**

If applicable, include error messages, stack traces, or any other debugging information.

**What version of Tink are you using?**

We use version 1.8.0:
```
implementation "com.google.crypto.tink:tink-android:1.8.0"
```

**Can you tell us more about your development environment?**

- Android Studio Flamingo 2022.2.1
- Android Gradle Plugin 8.0

**Is there anything else you'd like to add?**

Provide any additional context about the problem.

**Comment by morambro** [comment]
Hi @tonidero, I am not very familiar with R8. However, I noticed that tink-android 1.8's POM file doesn't specify the libraries' direct dependencies, so I fixed this in https://github.com/tink-crypto/tink-java/commit/ce8fb4a99fb567fcbc235d57aa1be8f397f9a4c7.

Could you please give `com.google.crypto.tink:tink-android:HEAD-SNAPSHOT` a try and let me know if the issue is still there?

**Comment by tonidero** [comment]
Hi @morambro, I tested that version. Interestingly, the issue with the `CanIgnoreReturnValue` annotation seems to have disappeared, but I'm still getting the same issue for the `Immutable` annotation:
```
Missing class com.google.errorprone.annotations.Immutable (referenced from: com.google.crypto.tink.util.Bytes)
```
Not sure of the reason for that change, maybe one of those dependencies is adding a rule to keep `CanIgnoreReturnValue` but not `Immutable`?

**Comment by morambro** [comment]
I just realized that our CI did not update `com.google.crypto.tink:tink-android:HEAD-SNAPSHOT`, so that one was actually an older snapshot. Very sorry about that, I am creating the actual snapshot now, will comment back when it is published.

In the meantime I was able to reproduce the issue modifying the Android example, and in my local setting `com.google.crypto.tink:tink-android:HEAD-SNAPSHOT` (the correct one) solves the issue.

**Comment by morambro** [comment]
The snapshot is published now, could you please give it a try?

**Comment by tonidero** [comment]
Yup that worked! Seems to build fine now with `com.google.crypto.tink:tink-android:HEAD-SNAPSHOT`. Thanks for the super quick fix!

**Comment by morambro** [comment]
Thanks for testing it! This will be included in the next release, will close this issue once the release is complete.

**Comment by morambro** [comment]
Tink Java 1.9.0 is released; [release notes](https://github.com/tink-crypto/tink-java/releases/tag/v1.9.0)

**Comment by ardevd** [comment]
I'm still seeing this error on v1.15.0
